# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Status
version:      0.04
version_from: lib/Thread/Status.pm
installdirs:  site
requires:
    Thread::Signal:                1.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
